# Generated by Django 4.0.2 on 2022-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Expediente', 'Expediente'), ('Mercearia', 'Mercearia'), ('Bebidas', 'Bebidas'), ('Alimento Não Perecível', 'Alimento Não Perecível'), ('Remédio', 'Remédio'), ('Protetor Solar', 'Protetor Solar')], max_length=50, null=True),
        ),
    ]
